title: JunHa Cha
description: Robotics Engineer | Software Engineer | Open Source Contributor
site_title: '@junha_cha Github Pages'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ckwnsgk
LAB_Homepage: https://sites.google.com/view/irasc/home
email: ckwnsgk1@gachon.ac.kr
keybase_username: JunHa Cha
instagram_username: z000_na
linkedin_username: 차준하/AI-소프트웨어학부(소프트웨어전공)
twitter_username: 차준하

# absolute or relative
profile_picture: assets/images/profile.jpeg
profile_picture_alt: 'JunHa Cha'

# Google Analytics ID
google_analytics: 